#!/usr/bin/env bash

case $1 in
  a)
    kubectl api-resources --verbs=list --namespaced -o name | sort | xargs -n 1 kubectl get --show-kind --ignore-not-found 2>/dev/null
    exit
    ;;
  app) r=application ;;
  cr)  r=clusterrole ;;
  crb) r=clusterrolebinding ;;
  d)   r=deploy ;;
  i)   r=ingress ;;
  j)   r=job ;;
  kc)  r=keycloak ;;
  kcc) r=keycloakclient ;;
  kcr) r=keycloakrealm ;;
  np)  r=networkpolicy ;;
  p)   r=pod ;;
  rb)  r=rolebinding ;;
  s)   r=service ;;
  sec) r=secret ;;
  *)   r=$1 ;;
esac

kubectl get "$r" "${@:2}"
