#!/usr/bin/env python

import subprocess
import sys

ladder_file = ".git/ladder"

def shell(cmd, *args):
    return subprocess.Popen([cmd] + list(args), stdout=subprocess.PIPE).stdout.read()

def edit():
    # TODO: vim
    shell("vim", ladder_file)

def git(git_cmd, *args):
    print " ".join(["git", git_cmd] + list(args))
    return shell("git", git_cmd, *args)

def current_branch():
    return git("symbolic-ref", "--quiet", "--short", "HEAD").strip()

def read_ladder():
    with open(ladder_file, "r") as f:
        return map(lambda l: l.strip(), f.readlines())

def main():
    cmd = sys.argv[1]
    if cmd == "down":
        # TODO: what if nothing down?
        cb = current_branch()
        ladder = read_ladder()
        cb_idx = ladder.index(cb)
        print ladder[cb_idx + 1]
    elif cmd == "list":
        print "\n".join(read_ladder())
    else:
        print "Unknown command"

main()

