#!/usr/bin/env python

import subprocess
import sys

stem_file = ".git/stems"

def shell(cmd, *args):
    subprocess.Popen([cmd] + args, stdout=subprocess.PIPE)

def edit():
    # TODO: vim
    shell("vim", stem_file)

def git(git_cmd, *args):
   shell("git", git_cmd, *args)

def read_stems():
    with open(stem_file, "r") as f:
        return f.read()

cmd = sys.argv[1]
if cmd == 'list':
    print read_stems()
else:
    print "Unknown command"

