#!/usr/bin/env bash

case $1 in
  a)
    kubectl api-resources --verbs=list --namespaced -o name | sort | xargs -n 1 kubectl get --show-kind --ignore-not-found
    exit
    ;;
  de|dep) r=deploy ;;
  rb)     r=rolebinding ;;
  se|sec) r=secret ;;
  *)      r=$1 ;;
esac

shift
kubectl get "$r" "$@"
