#!/usr/bin/env bash

case $1 in
  a)
    kubectl api-resources --verbs=list --namespaced -o name | sort | xargs -n 1 kubectl get --show-kind --ignore-not-found
    exit
    ;;
  d)   r=deploy ;;
  i)   r=ingress ;;
  p)   r=pod ;;
  rb)  r=rolebinding ;;
  s)   r=service ;;
  sec) r=secret ;;
  *)      r=$1 ;;
esac

kubectl get "$r" "${@:2}"
