#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  kubectl get secret
else
  kubectl get secret -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}' "$@"
fi

